
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 *
 * @author karma
 */
public class OptionsPanel extends javax.swing.JPanel {

	Renderer rend;
	
	//public ObjParser obj;
	public OptionsPanel() {

		initComponents();
	}
	
	public void setRenderer(Renderer rend) {
		
		this.rend = rend;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                jFileChooser1 = new javax.swing.JFileChooser();
                objectOffsetPanel = new javax.swing.JPanel();
                oxSpinner = new javax.swing.JSpinner();
                jLabel2 = new javax.swing.JLabel();
                oySpinner = new javax.swing.JSpinner();
                jLabel3 = new javax.swing.JLabel();
                ozSpinner = new javax.swing.JSpinner();
                jLabel4 = new javax.swing.JLabel();
                cameraPanel = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                nearPlaneSpinner = new javax.swing.JSpinner();
                farPlaneSpinner = new javax.swing.JSpinner();
                jLabel1 = new javax.swing.JLabel();
                scaleSpinner = new javax.swing.JSpinner();
                jPanel1 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                lxSpinner = new javax.swing.JSpinner();
                jLabel8 = new javax.swing.JLabel();
                lySpinner = new javax.swing.JSpinner();
                jLabel9 = new javax.swing.JLabel();
                lzSpinner = new javax.swing.JSpinner();
                jButton1 = new javax.swing.JButton();

                setLayout(new java.awt.GridBagLayout());

                objectOffsetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Object Offset", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
                objectOffsetPanel.setName("ObjecOffsetPanel"); // NOI18N
                objectOffsetPanel.setLayout(new java.awt.GridBagLayout());

                oxSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
                oxSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(oxSpinner, ""));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                objectOffsetPanel.add(oxSpinner, gridBagConstraints);

                jLabel2.setText("Y");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 15);
                objectOffsetPanel.add(jLabel2, gridBagConstraints);

                oySpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
                oySpinner.setEditor(new javax.swing.JSpinner.NumberEditor(oySpinner, ""));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                objectOffsetPanel.add(oySpinner, gridBagConstraints);

                jLabel3.setText("Z");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 4;
                gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 15);
                objectOffsetPanel.add(jLabel3, gridBagConstraints);

                ozSpinner.setModel(new javax.swing.SpinnerNumberModel(-2.0f, null, null, 1.0f));
                ozSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(ozSpinner, ""));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 4;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                objectOffsetPanel.add(ozSpinner, gridBagConstraints);

                jLabel4.setText("X");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 15);
                objectOffsetPanel.add(jLabel4, gridBagConstraints);

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                add(objectOffsetPanel, gridBagConstraints);

                cameraPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Camera", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
                cameraPanel.setLayout(new java.awt.GridBagLayout());

                jLabel5.setText("Near Plane");
                jLabel5.setToolTipText("");
                jLabel5.setAlignmentX(0.5F);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(jLabel5, gridBagConstraints);

                jLabel6.setText("Far  Plane");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(jLabel6, gridBagConstraints);

                nearPlaneSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(-100.0f), Float.valueOf(100.0f), Float.valueOf(0.1f)));
                nearPlaneSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(nearPlaneSpinner, "#.#"));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(nearPlaneSpinner, gridBagConstraints);

                farPlaneSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(10.0f), Float.valueOf(-100.0f), Float.valueOf(100.0f), Float.valueOf(0.1f)));
                farPlaneSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(farPlaneSpinner, "#.#"));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(farPlaneSpinner, gridBagConstraints);

                jLabel1.setText("Scale");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(jLabel1, gridBagConstraints);

                scaleSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(-10.0f), Float.valueOf(10.0f), Float.valueOf(0.1f)));
                scaleSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(scaleSpinner, "#.#"));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(scaleSpinner, gridBagConstraints);

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 4;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.weighty = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                add(cameraPanel, gridBagConstraints);
                cameraPanel.getAccessibleContext().setAccessibleName("");

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Light Position", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
                jPanel1.setLayout(new java.awt.GridBagLayout());

                jLabel7.setText("X");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
                jPanel1.add(jLabel7, gridBagConstraints);

                lxSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.1f));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                jPanel1.add(lxSpinner, gridBagConstraints);

                jLabel8.setText("Y");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
                jPanel1.add(jLabel8, gridBagConstraints);

                lySpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 0.1f));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                jPanel1.add(lySpinner, gridBagConstraints);

                jLabel9.setText("Z");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
                jPanel1.add(jLabel9, gridBagConstraints);

                lzSpinner.setModel(new javax.swing.SpinnerNumberModel(2.0f, null, null, 0.1f));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                jPanel1.add(lzSpinner, gridBagConstraints);

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                add(jPanel1, gridBagConstraints);

                jButton1.setText("Load Model");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                add(jButton1, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		
		//System.out.println("Load Model");
		int val = jFileChooser1.showOpenDialog(this);
		
		if (val == JFileChooser.APPROVE_OPTION) {
			
			File f = jFileChooser1.getSelectedFile();
			String fName = f.getName();
		}
		
        }//GEN-LAST:event_jButton1ActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel cameraPanel;
        public javax.swing.JSpinner farPlaneSpinner;
        private javax.swing.JButton jButton1;
        private javax.swing.JFileChooser jFileChooser1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        public javax.swing.JSpinner lxSpinner;
        public javax.swing.JSpinner lySpinner;
        public javax.swing.JSpinner lzSpinner;
        public javax.swing.JSpinner nearPlaneSpinner;
        private javax.swing.JPanel objectOffsetPanel;
        public javax.swing.JSpinner oxSpinner;
        public javax.swing.JSpinner oySpinner;
        public javax.swing.JSpinner ozSpinner;
        public javax.swing.JSpinner scaleSpinner;
        // End of variables declaration//GEN-END:variables
}
