/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karma
 */
public class OptionsPanel extends javax.swing.JPanel {

	/**
	 * Creates new form OptionsPanel
	 */
	public OptionsPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                objectOffsetPanel = new javax.swing.JPanel();
                xSpinner = new javax.swing.JSpinner();
                jLabel2 = new javax.swing.JLabel();
                ySpinner = new javax.swing.JSpinner();
                jLabel3 = new javax.swing.JLabel();
                zSpinner = new javax.swing.JSpinner();
                jLabel4 = new javax.swing.JLabel();
                cameraPanel = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                nearPlaneSpinner = new javax.swing.JSpinner();
                farPlaneSpinner = new javax.swing.JSpinner();
                jLabel1 = new javax.swing.JLabel();
                scaleSpinner = new javax.swing.JSpinner();
                jPanel1 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                jSpinner1 = new javax.swing.JSpinner();
                jLabel8 = new javax.swing.JLabel();
                jSpinner2 = new javax.swing.JSpinner();
                jLabel9 = new javax.swing.JLabel();
                jSpinner3 = new javax.swing.JSpinner();

                setLayout(new java.awt.GridBagLayout());

                objectOffsetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Object Offset", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
                objectOffsetPanel.setName("ObjecOffsetPanel"); // NOI18N
                objectOffsetPanel.setLayout(new java.awt.GridBagLayout());

                xSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
                xSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(xSpinner, ""));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                objectOffsetPanel.add(xSpinner, gridBagConstraints);

                jLabel2.setText("Y");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 15);
                objectOffsetPanel.add(jLabel2, gridBagConstraints);

                ySpinner.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
                ySpinner.setEditor(new javax.swing.JSpinner.NumberEditor(ySpinner, ""));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                objectOffsetPanel.add(ySpinner, gridBagConstraints);

                jLabel3.setText("Z");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 4;
                gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 15);
                objectOffsetPanel.add(jLabel3, gridBagConstraints);

                zSpinner.setModel(new javax.swing.SpinnerNumberModel(-2.0f, null, null, 1.0f));
                zSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(zSpinner, ""));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 4;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                objectOffsetPanel.add(zSpinner, gridBagConstraints);

                jLabel4.setText("X");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 15);
                objectOffsetPanel.add(jLabel4, gridBagConstraints);

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                add(objectOffsetPanel, gridBagConstraints);

                cameraPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Camera", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
                cameraPanel.setLayout(new java.awt.GridBagLayout());

                jLabel5.setText("Near Plane");
                jLabel5.setToolTipText("");
                jLabel5.setAlignmentX(0.5F);
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(jLabel5, gridBagConstraints);

                jLabel6.setText("Far  Plane");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(jLabel6, gridBagConstraints);

                nearPlaneSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(-100.0f), Float.valueOf(100.0f), Float.valueOf(0.1f)));
                nearPlaneSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(nearPlaneSpinner, "#.#"));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(nearPlaneSpinner, gridBagConstraints);

                farPlaneSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(10.0f), Float.valueOf(-100.0f), Float.valueOf(100.0f), Float.valueOf(0.1f)));
                farPlaneSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(farPlaneSpinner, "#.#"));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(farPlaneSpinner, gridBagConstraints);

                jLabel1.setText("Scale");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(jLabel1, gridBagConstraints);

                scaleSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(-10.0f), Float.valueOf(10.0f), Float.valueOf(0.1f)));
                scaleSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(scaleSpinner, "#.#"));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                cameraPanel.add(scaleSpinner, gridBagConstraints);

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.weighty = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                add(cameraPanel, gridBagConstraints);
                cameraPanel.getAccessibleContext().setAccessibleName("");

                jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Light Position", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
                jPanel1.setLayout(new java.awt.GridBagLayout());

                jLabel7.setText("X");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
                jPanel1.add(jLabel7, gridBagConstraints);

                jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 0));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 1;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                jPanel1.add(jSpinner1, gridBagConstraints);

                jLabel8.setText("Y");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
                jPanel1.add(jLabel8, gridBagConstraints);

                jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 0));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                jPanel1.add(jSpinner2, gridBagConstraints);

                jLabel9.setText("Z");
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 15);
                jPanel1.add(jLabel9, gridBagConstraints);

                jSpinner3.setModel(new javax.swing.SpinnerNumberModel(2, null, null, 0));
                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 2;
                gridBagConstraints.gridy = 3;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.weightx = 1.0;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                jPanel1.add(jSpinner3, gridBagConstraints);

                gridBagConstraints = new java.awt.GridBagConstraints();
                gridBagConstraints.gridx = 1;
                gridBagConstraints.gridy = 2;
                gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
                gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
                gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
                add(jPanel1, gridBagConstraints);
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel cameraPanel;
        public javax.swing.JSpinner farPlaneSpinner;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JSpinner jSpinner1;
        private javax.swing.JSpinner jSpinner2;
        private javax.swing.JSpinner jSpinner3;
        public javax.swing.JSpinner nearPlaneSpinner;
        private javax.swing.JPanel objectOffsetPanel;
        public javax.swing.JSpinner scaleSpinner;
        public javax.swing.JSpinner xSpinner;
        public javax.swing.JSpinner ySpinner;
        public javax.swing.JSpinner zSpinner;
        // End of variables declaration//GEN-END:variables
}
